Repository chanzuckerberg/sci-components, pull requests merged in 2023-08, with the labels that each got.

#548 feat(navigationjumpto): emit the index of the navigation tab on scroll
  packages/components/src/core/NavigationJumpTo/NavigationJumpTo.namespace-test.tsx
  packages/components/src/core/NavigationJumpTo/index.tsx
  packages/components/src/core/NavigationJumpTo/style.ts
Labels: Ready for review

#547 feat(icon): add ChevronLeft2 and ChevronRight2 icons
  packages/components/src/common/svgs/IconChevronLeft2Small.svg
  packages/components/src/common/svgs/IconChevronRight2Small.svg
  packages/components/src/core/Icon/map.ts
Labels: Eng

#551 feat(storybook): upgrade
  .storybook/main.js
  package.json
  yarn.lock
Labels: Ready for review

#553 feat(autocomplete): implement Autocomplete component
  .storybook/manager-head.html
  package.json
  packages/components/src/core/Autocomplete/Autocomplete.namespace-test.tsx
  packages/components/src/core/Autocomplete/__snapshots__/index.test.tsx.snap
  packages/components/src/core/Autocomplete/index.stories.tsx
  packages/components/src/core/Autocomplete/index.test.tsx
  packages/components/src/core/Autocomplete/index.tsx
  packages/components/src/core/Autocomplete/style.ts
  packages/components/src/core/Dropdown/index.test.tsx
  packages/components/src/core/DropdownMenu/index.stories.tsx
  packages/components/src/index.ts
  yarn.lock
Labels: Ready for release

#565 fix(inputdropdown): fix UserInput and Open state styles
  packages/components/src/core/ComplexFilter/__snapshots__/index.test.tsx.snap
  packages/components/src/core/Dropdown/__snapshots__/index.test.tsx.snap
  packages/components/src/core/InputDropdown/__snapshots__/index.test.tsx.snap
  packages/components/src/core/InputDropdown/index.stories.tsx
  packages/components/src/core/InputDropdown/index.tsx
  packages/components/src/core/InputDropdown/style.ts
Labels: Bug, Ready for release

#576 fix(callout): add expandable prop to Callout + upgrade Storybook
  package.json
  packages/components/src/core/Callout/index.stories.tsx
  yarn.lock
Labels: Ready for review
