Repository chanzuckerberg/sci-components, pull requests merged in 2023-05, with the labels that each got.

#446 feat(icon): add xs and s upload icon
  packages/components/src/common/svgs/IconUploadSmall.svg
  packages/components/src/core/Icon/map.ts
Labels: Eng

#451 feat(dropdown): new tests for the dropdown component
  package.json
  packages/components/package.json
  packages/components/src/core/Dropdown/index.stories.tsx
  packages/components/src/core/Dropdown/index.test.tsx
  packages/components/src/core/Dropdown/index.tsx
  packages/components/src/core/DropdownMenu/GITHUB_LABELS.tsx
  yarn.lock
Labels: Ready for release

#459 refactor(dropdownmenu): update storybook stories and remove InputDrop…
  package.json
  packages/components/package.json
  packages/components/src/core/Dropdown/index.stories.tsx
  packages/components/src/core/DropdownMenu/__snapshots__/index.test.tsx.snap
  packages/components/src/core/DropdownMenu/index.stories.tsx
  packages/components/src/core/DropdownMenu/index.test.tsx
  packages/components/src/core/InputDropdown/index.tsx
  packages/data-viz/package.json
  yarn.lock
Labels: Ready for review
