Repository chanzuckerberg/sci-components, pull requests merged in 2023-07, with the labels that each got.

#535 docs(icon): add documentation to GitHub repo about uploading new icon…
  packages/components/docs/how-to-add-icon.md
Labels: Documentation

#536 feat(inputdropdown): implement new redesigned inputdropdown
  packages/components/src/core/Banner/__snapshots__/banner.test.tsx.snap
  packages/components/src/core/ButtonIcon/__snapshots__/index.test.tsx.snap
  packages/components/src/core/ButtonIcon/style.ts
  packages/components/src/core/CellHeader/__snapshots__/index.test.tsx.snap
  packages/components/src/core/ComplexFilter/__snapshots__/index.test.tsx.snap
  packages/components/src/core/Dialog/__snapshots__/index.test.tsx.snap
  packages/components/src/core/Dropdown/__snapshots__/index.test.tsx.snap
  packages/components/src/core/DropdownMenu/index.stories.tsx
  packages/components/src/core/InputDropdown/InputDropdown.namespace-test.tsx
  packages/components/src/core/InputDropdown/__snapshots__/index.test.tsx.snap
  packages/components/src/core/InputDropdown/index.stories.tsx
  packages/components/src/core/InputDropdown/index.tsx
  packages/components/src/core/InputDropdown/style.ts
  packages/components/src/core/Pagination/__snapshots__/index.test.tsx.snap
  packages/components/src/core/Table/__snapshots__/index.test.tsx.snap
  packages/components/src/core/TableHeader/__snapshots__/index.test.tsx.snap
Labels: Ready for review

#538 fix(icon): iconVirusLarge icon
  packages/components/src/common/svgs/IconVirusLarge.svg
Labels: Bug
