Repository chanzuckerberg/sci-components, pull requests merged in 2024-11, with the labels that each got.

#891 fix(segmentedcontrol): allow all buttons to be deselected
  packages/components/src/core/SegmentedControl/index.tsx
Labels: P0, Feature Request, Eng, Ready for review

#884 feat(styles/common): mobile font styles
  packages/components/src/core/Callout/style.ts
  packages/components/src/core/Notification/style.ts
  packages/components/src/core/styles/common/SDSAppTheme.ts
  packages/components/src/core/styles/common/makeThemeOptions.ts
  packages/components/src/core/styles/common/mixins/fonts.ts
  packages/components/src/core/styles/common/types.ts
Labels: Ready for review

#892 feat(designtokens): add narrow fonts to design tokens
  packages/components/src/common/styles-dictionary/build.mjs
  packages/components/src/common/styles-dictionary/css/variables.css
  packages/components/src/common/styles-dictionary/custom-formatters/cssFormatter.mjs
  packages/components/src/common/styles-dictionary/custom-formatters/scssFormatter.mjs
  packages/components/src/common/styles-dictionary/custom-formatters/tailwindFormatter.mjs
  packages/components/src/common/styles-dictionary/design-tokens/font.json
  packages/components/src/common/styles-dictionary/json/tailwind.json
  packages/components/src/common/styles-dictionary/scss/_variables.scss
Labels: P0, Eng, Ready for review

#888 feat(breakpoints): added new SDS breakpoints
  packages/components/src/common/styles-dictionary/css/variables.css
  packages/components/src/common/styles-dictionary/custom-formatters/tailwindFormatter.mjs
  packages/components/src/common/styles-dictionary/design-tokens/breakpoints.json
  packages/components/src/common/styles-dictionary/json/tailwind.json
  packages/components/src/common/styles-dictionary/scss/_variables.scss
  packages/components/src/core/Bases/Breakpoints/__storybook__/constants.tsx
  packages/components/src/core/Bases/Breakpoints/__storybook__/index.stories.tsx
  packages/components/src/core/Bases/Breakpoints/__storybook__/stories/default.tsx
  packages/components/src/core/Bases/Breakpoints/__storybook__/style.ts
  packages/components/src/core/Dropdown/__storybook__/stories/insideModal.tsx
  packages/components/src/core/styles/common/makeThemeOptions.ts
  packages/components/src/core/styles/common/selectors/theme.ts
  packages/components/src/core/styles/common/types.ts
Labels: Eng, Ready for review

#895 fix(inputs): fix border color of inputs based on intent prop
  packages/components/src/core/Autocomplete/__storybook__/constants.tsx
  packages/components/src/core/Autocomplete/__storybook__/index.stories.tsx
  packages/components/src/core/Autocomplete/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/Autocomplete/components/AutocompleteBase/index.tsx
  packages/components/src/core/InputCheckbox/__storybook__/constants.ts
  packages/components/src/core/InputCheckbox/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/InputCheckbox/styles.ts
  packages/components/src/core/InputDropdown/style.ts
  packages/components/src/core/InputRadio/__storybook__/stories/default.tsx
  packages/components/src/core/InputRadio/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/InputRadio/style.ts
  packages/components/src/core/InputSearch/style.ts
  packages/components/src/core/InputText/style.ts
  packages/components/src/core/Table/__tests__/__snapshots__/index.test.tsx.snap
Labels: Bug, P0, Eng, Ready for review

#900 refactor(tooltip): rename sdsStyle prop to invertStyle
  packages/components/src/common/warnings.ts
  packages/components/src/core/Tooltip/__storybook__/constants.ts
  packages/components/src/core/Tooltip/__storybook__/index.stories.tsx
  packages/components/src/core/Tooltip/index.tsx
  packages/components/src/core/Tooltip/style.ts
Labels: P1, Eng

#906 refactor(navigationjumpto): refactor the onChange prop
  packages/components/src/core/NavigationJumpTo/index.tsx
Labels: P0, Feature Request, Ready for review
