Repository chanzuckerberg/sci-components, pull requests merged in 2024-10, with the labels that each got.

#857 feat(inputs): add positive intent to input compoennts
  packages/components/src/core/Autocomplete/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/ComplexFilter/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/Dropdown/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/InputCheckbox/__storybook__/index.stories.tsx
  packages/components/src/core/InputCheckbox/styles.ts
  packages/components/src/core/InputDropdown/__storybook__/index.stories.tsx
  packages/components/src/core/InputDropdown/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/InputDropdown/style.ts
  packages/components/src/core/InputRadio/__storybook__/index.stories.tsx
  packages/components/src/core/InputRadio/style.ts
  packages/components/src/core/InputSearch/__storybook__/index.stories.tsx
  packages/components/src/core/InputSearch/style.ts
  packages/components/src/core/InputText/__storybook__/index.stories.tsx
  packages/components/src/core/InputText/style.ts
Labels: Feature Request, Eng, Ready for review

#856 feat(borders): new `thick` and `extraThick` border variables
  packages/components/src/common/styles-dictionary/css/variables.css
  packages/components/src/common/styles-dictionary/design-tokens/borders.json
  packages/components/src/common/styles-dictionary/scss/_variables.scss
  packages/components/src/core/Notification/style.ts
  packages/components/src/core/styles/common/SDSAppTheme.ts
  packages/components/src/core/styles/common/types.ts
Labels: Eng, Ready for review

#850 feat(Panel): implement panel component
  packages/components/src/core/Panel/__storybook__/constants.ts
  packages/components/src/core/Panel/__storybook__/index.stories.tsx
  packages/components/src/core/Panel/__storybook__/stories/customCloseButton.tsx
  packages/components/src/core/Panel/__storybook__/stories/default.tsx
  packages/components/src/core/Panel/__storybook__/stories/test.tsx
  packages/components/src/core/Panel/__tests__/Panel.namespace-test.tsx
  packages/components/src/core/Panel/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/Panel/__tests__/index.test.tsx
  packages/components/src/core/Panel/components/PanelHeader/index.tsx
  packages/components/src/core/Panel/components/PanelHeader/style.ts
  packages/components/src/core/Panel/components/PanelHeaderClose/index.tsx
  packages/components/src/core/Panel/components/PanelHeaderClose/style.ts
  packages/components/src/core/Panel/index.tsx
  packages/components/src/core/Panel/style.ts
  packages/components/src/core/styles/common/makeThemeOptions.ts
  packages/components/src/index.ts
Labels: Eng, Ready for review

#855 fix(dropdownmenu): fix header visibility and extra margin issue
  packages/components/src/core/DropdownMenu/index.tsx
Labels: Eng, Ready for review

#858 fix(inputtext): remove min-width from InputText and InputSearch
  packages/components/src/core/Autocomplete/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/Icon/__storybook__/stories/iconBank.tsx
  packages/components/src/core/InputSearch/__storybook__/stories/default.tsx
  packages/components/src/core/InputSearch/__storybook__/stories/test.tsx
  packages/components/src/core/InputSearch/style.ts
  packages/components/src/core/InputText/__storybook__/stories/default.tsx
  packages/components/src/core/InputText/style.ts
Labels: Bug, Eng, Ready for review

#869 feat(SegmentedControl): add disabled state in button definition
  packages/components/src/core/SegmentedControl/__storybook__/index.stories.tsx
  packages/components/src/core/SegmentedControl/__storybook__/stories/controlledSegmentedControl.tsx
  packages/components/src/core/SegmentedControl/__storybook__/stories/default.tsx
  packages/components/src/core/SegmentedControl/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/SegmentedControl/index.tsx
  packages/components/src/core/SegmentedControl/style.ts
Labels: P0, Feature Request, Eng, Ready for review

#866 fix(tag): fix custom coloring of Tag component
  packages/components/src/core/Tag/style.ts
Labels: Bug, Eng, Ready for release

#876 refactor(icons): refactor Book icon large
  packages/components/src/common/svgs/IconBookLarge.svg
Labels: Feature Request, Eng, Design, Ready for review

#867 refactor(panel): refactor Panel component
  packages/components/src/core/Panel/__storybook__/index.stories.tsx
  packages/components/src/core/Panel/__storybook__/stories/default.tsx
  packages/components/src/core/Panel/__storybook__/stories/scrollBehavior.tsx
  packages/components/src/core/Panel/__storybook__/stories/test.tsx
  packages/components/src/core/Panel/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/Panel/index.tsx
  packages/components/src/core/Panel/style.ts
Labels: P0, Feature Request, Eng, Ready for release

#880 fix(link): fix multi-line link text-decorations
  packages/components/src/core/Link/__storybook__/index.stories.tsx
  packages/components/src/core/Link/__storybook__/stories/longText.tsx
  packages/components/src/core/Link/style.ts
Labels: Bug, P0, Eng, Ready for review

#883 build: set interop to auto for output config
  packages/components/rollup.config.mjs
  packages/data-viz/rollup.config.mjs
Labels: Bug, P0, Eng
