Repository chanzuckerberg/sci-components, pull requests merged in 2025-03, with the labels that each got.

#937 refactor(navigationheader): vcp changes
  packages/components/src/common/styles-dictionary/css/variables.css
  packages/components/src/core/Button/index.tsx
  packages/components/src/core/ContentCard/ContentCard.types.ts
  packages/components/src/core/ContentCard/__storybook__/index.stories.tsx
  packages/components/src/core/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/ContentCard/components/ContentCardActions/index.tsx
  packages/components/src/core/ContentCard/components/ContentCardImageMedia/index.tsx
  packages/components/src/core/ContentCard/components/ContentCardTitle/index.tsx
  packages/components/src/core/ContentCard/index.tsx
  packages/components/src/core/ContentCard/style.ts
  packages/components/src/core/NavigationHeader/__storybook__/index.stories.tsx
  packages/components/src/core/NavigationHeader/__storybook__/stories/default.tsx
  packages/components/src/core/NavigationHeader/__tests__/NavigationHeader.namespace-test.tsx
  packages/components/src/core/NavigationHeader/__tests__/index.test.tsx
  packages/components/src/core/NavigationHeader/components/NavigationHeaderSecondaryNav/index.tsx
  packages/components/src/core/NavigationHeader/components/NavigationHeaderSecondaryNav/style.ts
  packages/components/src/core/NavigationHeader/index.tsx
  packages/components/src/core/NavigationHeader/style.ts
Labels: Bug, Ready for review

#939 fix(ContentCard): Fixed ContentCard content height + Fixed TS types on CC
  packages/components/src/core/Button/index.tsx
  packages/components/src/core/ContentCard/ContentCard.types.ts
  packages/components/src/core/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/ContentCard/index.tsx
  packages/components/src/core/ContentCard/style.ts
Labels: Bug, Ready for review

#924 chore(styles/common): add borders to makeSdsSemanticAppTheme util
  packages/components/src/core/styles/common/SDSAppTheme.ts
Labels: P0, Ready for review

#919 fix(ButtonDropdown): Sync Button props type
  packages/components/src/core/Button/index.tsx
  packages/components/src/core/ButtonDropdown/index.tsx
Labels: P0, Ready for release
