Repository chanzuckerberg/sci-components, pull requests merged in 2025-02, with the labels that each got.

#885 feat(NavigationHeader): implement NavigationHeader component
  package.json
  packages/components/src/common/styles-dictionary/css/variables.css
  packages/components/src/common/styles-dictionary/design-tokens/colors.json
  packages/components/src/common/styles-dictionary/json/tailwind.json
  packages/components/src/common/styles-dictionary/scss/_variables.scss
  packages/components/src/common/warnings.ts
  packages/components/src/core/Autocomplete/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/Banner/__tests__/__snapshots__/banner.test.tsx.snap
  packages/components/src/core/Button/__storybook__/stories/default.tsx
  packages/components/src/core/Button/__storybook__/stories/screenshot.tsx
  packages/components/src/core/Button/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/Button/index.tsx
  packages/components/src/core/Button/style.ts
  packages/components/src/core/ButtonDropdown/__storybook__/index.stories.tsx
  packages/components/src/core/ButtonDropdown/__storybook__/stories/default.tsx
  packages/components/src/core/ButtonDropdown/__tests__/ButtonDropdown.namespace-test.tsx
  packages/components/src/core/ButtonDropdown/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/ButtonDropdown/index.tsx
  packages/components/src/core/ButtonIcon/style.ts
  packages/components/src/core/Callout/__tests__/Callout.namespace-test.tsx
  packages/components/src/core/Callout/index.tsx
  packages/components/src/core/ComplexFilter/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/Dialog/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/Dialog/components/DialogTitle/index.tsx
  packages/components/src/core/Dropdown/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/InputDropdown/__storybook__/stories/default.tsx
  packages/components/src/core/InputDropdown/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/InputDropdown/style.ts
  packages/components/src/core/InputSearch/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/InputSearch/index.tsx
  packages/components/src/core/InputSearch/style.ts
  packages/components/src/core/NavigationHeader/__storybook__/constants.tsx
  packages/components/src/core/NavigationHeader/__storybook__/index.stories.tsx
  packages/components/src/core/NavigationHeader/__storybook__/stories/default.tsx
  packages/components/src/core/NavigationHeader/__storybook__/stories/test.tsx
  packages/components/src/core/NavigationHeader/__tests__/NavigationHeader.namespace-test.tsx
  packages/components/src/core/NavigationHeader/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/NavigationHeader/__tests__/index.test.tsx
  packages/components/src/core/NavigationHeader/components/NavigationHeaderPrimaryNav/index.tsx
  packages/components/src/core/NavigationHeader/components/NavigationHeaderPrimaryNav/style.ts
  packages/components/src/core/NavigationHeader/components/NavigationHeaderSecondaryNav/index.tsx
  packages/components/src/core/NavigationHeader/components/NavigationHeaderSecondaryNav/style.ts
  packages/components/src/core/NavigationHeader/components/style.ts
  packages/components/src/core/NavigationHeader/index.tsx
  packages/components/src/core/NavigationHeader/style.ts
  packages/components/src/core/Pagination/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/Panel/__storybook__/stories/default.tsx
  packages/components/src/core/Tag/__storybook__/stories/default.tsx
  packages/components/src/core/TagFilter/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/Tooltip/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/Tooltip/style.ts
  packages/components/src/core/styles/common/makeThemeOptions.ts
  packages/components/src/core/styles/common/mixins/fonts.ts
  packages/components/src/core/styles/common/types.ts
  packages/components/src/index.ts
Labels: Feature Request, Eng, Ready for review, Zeroheight Technical Documentation

#935 feat(contentcard): first implementation
  packages/components/src/common/styles-dictionary/css/variables.css
  packages/components/src/common/styles-dictionary/design-tokens/colors.json
  packages/components/src/common/styles-dictionary/json/tailwind.json
  packages/components/src/common/styles-dictionary/scss/_variables.scss
  packages/components/src/common/utils.ts
  packages/components/src/common/warnings.ts
  packages/components/src/core/Autocomplete/components/AutocompleteBase/style.ts
  packages/components/src/core/Button/style.ts
  packages/components/src/core/ContentCard/ContentCard.types.ts
  packages/components/src/core/ContentCard/__storybook__/constants.tsx
  packages/components/src/core/ContentCard/__storybook__/index.stories.tsx
  packages/components/src/core/ContentCard/__storybook__/stories/default.tsx
  packages/components/src/core/ContentCard/__storybook__/stories/test.tsx
  packages/components/src/core/ContentCard/__tests__/ContentCard.namespace-test.tsx
  packages/components/src/core/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/ContentCard/__tests__/index.test.tsx
  packages/components/src/core/ContentCard/components/ContentCardActions/index.tsx
  packages/components/src/core/ContentCard/components/ContentCardActions/style.ts
  packages/components/src/core/ContentCard/components/ContentCardImageMedia/index.tsx
  packages/components/src/core/ContentCard/components/ContentCardImageMedia/style.ts
  packages/components/src/core/ContentCard/components/ContentCardTitle/index.tsx
  packages/components/src/core/ContentCard/components/ContentCardTitle/style.ts
  packages/components/src/core/ContentCard/index.tsx
  packages/components/src/core/ContentCard/style.ts
  packages/components/src/core/InputDropdown/style.ts
  packages/components/src/core/InputRadio/style.ts
  packages/components/src/core/InputSearch/style.ts
  packages/components/src/core/NavigationHeader/__storybook__/stories/default.tsx
  packages/components/src/core/NavigationHeader/components/NavigationHeaderPrimaryNav/style.ts
  packages/components/src/core/NavigationHeader/style.ts
  packages/components/src/core/NavigationJumpTo/style.ts
  packages/components/src/core/SegmentedControl/style.ts
  packages/components/src/core/TableHeader/style.ts
  packages/components/src/core/Tabs/style.tsx
  packages/components/src/core/styles/common/makeThemeOptions.ts
  packages/components/src/core/styles/common/mixins/a11y.ts
  packages/components/src/core/styles/common/mixins/fonts.ts
  packages/components/src/core/styles/common/types.ts
  packages/components/src/index.ts
  packages/components/tsconfig-namespace-check.json
Labels: Feature Request, Ready for review

#886 feat(NavigationFooter): implement NavigationFooter component
  packages/components/src/core/NavigationFooter/NavigationFooter.types.ts
  packages/components/src/core/NavigationFooter/__storybook__/constants.tsx
  packages/components/src/core/NavigationFooter/__storybook__/index.stories.tsx
  packages/components/src/core/NavigationFooter/__storybook__/stories/default.tsx
  packages/components/src/core/NavigationFooter/__storybook__/stories/test.tsx
  packages/components/src/core/NavigationFooter/__tests__/NavigationFooter.namespace-test.tsx
  packages/components/src/core/NavigationFooter/__tests__/__snapshots__/index.test.tsx.snap
  packages/components/src/core/NavigationFooter/__tests__/index.test.tsx
  packages/components/src/core/NavigationFooter/components/FooterLink/index.tsx
  packages/components/src/core/NavigationFooter/components/FooterLink/style.ts
  packages/components/src/core/NavigationFooter/components/NavItem/index.tsx
  packages/components/src/core/NavigationFooter/components/NavItem/style.ts
  packages/components/src/core/NavigationFooter/index.tsx
  packages/components/src/core/NavigationFooter/style.ts
  packages/components/src/core/NavigationHeader/style.ts
  packages/components/src/index.ts
Labels: Eng, Ready for release, Zeroheight Technical Documentation
